"""Add description column to portfolios

Revision ID: e697e5798ce7
Revises: create_tables
Create Date: 2024-04-20 09:23:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'e697e5798ce7'
down_revision = 'create_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sectors')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('total_gain')
        batch_op.drop_column('day_change')
        batch_op.drop_column('total_value')
        batch_op.drop_column('total_gain_percent')
        batch_op.drop_column('day_change_percent')
        batch_op.drop_column('cash_value')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pe_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Integer(), nullable=True))
        batch_op.alter_column('cost_basis',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('day_change_dollar')
        batch_op.drop_column('market_value')
        batch_op.drop_column('description')
        batch_op.drop_column('security_type')
        batch_op.drop_column('day_change_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_change_percent', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('security_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('market_value', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('day_change_dollar', sa.FLOAT(), nullable=True))
        batch_op.alter_column('cost_basis',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('volume')
        batch_op.drop_column('eps')
        batch_op.drop_column('market_cap')
        batch_op.drop_column('pe_ratio')
        batch_op.drop_column('industry')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('day_change_percent', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_gain_percent', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('day_change', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_gain', sa.FLOAT(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('description')

    op.create_table('sectors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('market_value', sa.FLOAT(), nullable=False),
    sa.Column('percentage', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
